kind: pipeline
name: default
    
steps:
  - name: build
    image: node
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - npm install
      - npm test
      - npm run build

  - name: cleanup
    image: docker
    commands:
      - docker system prune -f
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
    when:
      status: failure

volumes:
  - name: cache
    host:
       path: /var/lib/cache
  - name: docker1
      host:
        path: /var/run/docker.sock
  - name: docker2
      host:
        path: /var/lib/docker