kind: pipeline
name: default
    
steps:
  - name: build
    image: docker
    commands:
      - docker build . -t build-image -f Dockerfile.build
      - docker create --name build-container build-image
      - docker cp build-container:/build-image ./src/build
      - docker rm build-container
    volumes:
      - name: build
        path: /build
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker

  - name: publish  
    image: plugins/gh-pages
    settings:
      username:
        fromSecret: GITHUB_USERNAME
      password:
        fromSecret: GITHUB_PASSWORD
      pages_directory: /build
      
volumes:
  - name: build
    temp: {}
  - name: docker1
    host:
      path: /var/run/docker.sock
  - name: docker2
    host:
      path: /var/lib/docker