kind: pipeline
name: default
    
steps:
  - name: build
    image: node
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - npm install
      - npm test
      - npm run build

volumes:
  - name: cache
    host:
       path: /var/lib/cache