kind: pipeline
name: default
    
steps:
  - name: build
    image: node
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - npm install
      - npm test
      - npm run build

  - name: cleanup
    image: docker
    commands:
      - docker system prune -f
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    when:
      status: failure

volumes:
- name: cache
  host:
    path: /var/lib/cache